name: Deployment

on:
  push:
    branches:
      - stage
      - production
      
jobs:   
  stage-deploy:
    if: github.ref == 'refs/heads/stage'
    name: Stage Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_GITHUB_KEY }}
      - name: Do Server Actions (e.g. Build, Clear Cache, ...)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ~/htdocs/devpoint.salahineo.com/DevPoint/
            git pull origin stage
  
  production-deploy:
    if: github.ref == 'refs/heads/production'
    name: Production Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_GITHUB_KEY }}
      - name: Do Server Actions (e.g. Build, Clear Cache, ...)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ~/htdocs/devpoint.salahineo.com/DevPoint/
            git pull origin production
