name: Deployment

on:
  push:
    branches:
      - stage
      - production
      
jobs:   
  stage-deploy:
    if: github.ref == 'refs/heads/staging'
    name: Stage Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Do Server Actions (e.g. Build, Clear Cache, ...)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ~/htdocs/devpoint.salahineo.com/
            whoami
  
  production-deploy:
    if: github.ref == 'refs/heads/production'
    name: Production Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Do Server Actions (e.g. Build, Clear Cache, ...)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ~/htdocs/devpoint.salahineo.com/
            whoami
